language: go

go:
  - 1.7.x
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

script:
  - go get ./...

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}/{{.Dir}}/{{.Dir}}"
  # make an dist/OS_ARCH.tar.gz for each, but put the binary in the top level
  - for i in $(find dist -mindepth 1 -maxdepth 1 -type d); do tar -czvf "$i".tar.gz -C "$i" "."; done
  - ghr --username bengadbois --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
deploy:
  provider: script
  script: ghr --username bengadbois --token $GITHUB_TOKEN --replace --debug $(git tag -l --contains HEAD) dist/
  skip_cleanup: true
  on:
    tags: true
    go: 1.8
